
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_CONTINETS = "GET_CONTINETS";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_NAME_COUNTRY = "GET_NAME_COUNTRY";
export const GET_DETAIL = "GET_DETAIL";
export const POST_ACTIVITY = "POST_ACTIVITY";
export const FILTER_CONTINETS = "FILTER_CONTINETS";
export const FILTER_ACTIVITIES ="FILTER_ACTVITIES";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
